import {
  ServiceCategory,
  ServiceItem,
  SubscriptionPlan,
  Provider,
  Booking,
} from "@/types";

export const SERVICE_CATEGORIES: ServiceItem[] = [
  {
    category: "plumbing",
    name: "Plumbing",
    icon: "droplets",
    description: "Pipe repairs, leak fixes, installations",
    startingPrice: 60,
  },
  {
    category: "cleaning",
    name: "Cleaning",
    icon: "sparkles",
    description: "Deep clean, regular, move-in/out",
    startingPrice: 45,
  },
  {
    category: "tutoring",
    name: "Tutoring",
    icon: "book-open",
    description: "Math, science, languages, test prep",
    startingPrice: 35,
  },
  {
    category: "beauty",
    name: "Beauty",
    icon: "scissors",
    description: "Hair, nails, makeup, spa services",
    startingPrice: 50,
  },
  {
    category: "handyman",
    name: "Handyman",
    icon: "wrench",
    description: "Repairs, assembly, maintenance",
    startingPrice: 55,
  },
  {
    category: "electrical",
    name: "Electrical",
    icon: "zap",
    description: "Wiring, fixtures, panel upgrades",
    startingPrice: 70,
  },
  {
    category: "painting",
    name: "Painting",
    icon: "paintbrush",
    description: "Interior, exterior, accent walls",
    startingPrice: 80,
  },
  {
    category: "moving",
    name: "Moving",
    icon: "truck",
    description: "Local moves, packing, loading",
    startingPrice: 90,
  },
  {
    category: "landscaping",
    name: "Landscaping",
    icon: "trees",
    description: "Lawn care, garden, tree trimming",
    startingPrice: 50,
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    tier: "free",
    name: "Free",
    price: 0,
    period: "month",
    features: [
      "Up to 3 bookings/month",
      "Basic provider matching",
      "In-app messaging",
      "Standard support",
    ],
    jobLimit: 3,
  },
  {
    tier: "basic",
    name: "Basic",
    price: 9.99,
    period: "month",
    features: [
      "Up to 15 bookings/month",
      "Priority matching",
      "In-app messaging",
      "GPS tracking",
      "Email support",
      "Booking history",
    ],
    jobLimit: 15,
  },
  {
    tier: "pro",
    name: "Pro",
    price: 24.99,
    period: "month",
    features: [
      "Unlimited bookings",
      "Top provider priority",
      "Real-time GPS tracking",
      "In-app chat & video",
      "Priority support",
      "Advanced analytics",
      "Verified badge",
      "Cancellation protection",
    ],
    jobLimit: null,
    highlighted: true,
  },
  {
    tier: "enterprise",
    name: "Enterprise",
    price: 79.99,
    period: "month",
    features: [
      "Everything in Pro",
      "Multi-location support",
      "Team management",
      "Dedicated account manager",
      "Custom invoicing",
      "SLA guarantee",
      "API access",
      "White-label options",
    ],
    jobLimit: null,
  },
];

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: "p1",
    email: "marcus.johnson@email.com",
    name: "Marcus Johnson",
    role: "provider",
    phone: "+1 (555) 234-5678",
    categories: ["plumbing", "handyman"],
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 65,
    bio: "Licensed plumber with 12+ years experience. Quick, reliable, and professional.",
    isVerified: true,
    isAvailable: true,
    documentsUploaded: true,
    completedJobs: 342,
    location: { lat: 40.7128, lng: -74.006, address: "Manhattan, NY" },
    createdAt: "2023-01-15T00:00:00Z",
  },
  {
    id: "p2",
    email: "sarah.chen@email.com",
    name: "Sarah Chen",
    role: "provider",
    phone: "+1 (555) 345-6789",
    categories: ["cleaning"],
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 45,
    bio: "Eco-friendly cleaning specialist. Making your space sparkle since 2019.",
    isVerified: true,
    isAvailable: true,
    documentsUploaded: true,
    completedJobs: 256,
    location: { lat: 40.7589, lng: -73.9851, address: "Midtown, NY" },
    createdAt: "2023-03-20T00:00:00Z",
  },
  {
    id: "p3",
    email: "david.martinez@email.com",
    name: "David Martinez",
    role: "provider",
    phone: "+1 (555) 456-7890",
    categories: ["electrical", "handyman"],
    rating: 4.7,
    reviewCount: 64,
    hourlyRate: 75,
    bio: "Certified electrician. Safe, code-compliant work every time.",
    isVerified: true,
    isAvailable: false,
    documentsUploaded: true,
    completedJobs: 198,
    location: { lat: 40.7282, lng: -73.7949, address: "Queens, NY" },
    createdAt: "2023-06-10T00:00:00Z",
  },
  {
    id: "p4",
    email: "emily.watson@email.com",
    name: "Emily Watson",
    role: "provider",
    phone: "+1 (555) 567-8901",
    categories: ["tutoring"],
    rating: 5.0,
    reviewCount: 42,
    hourlyRate: 40,
    bio: "SAT/ACT prep expert & math tutor. Harvard grad, patient and effective.",
    isVerified: true,
    isAvailable: true,
    documentsUploaded: true,
    completedJobs: 156,
    location: { lat: 40.7484, lng: -73.9967, address: "Chelsea, NY" },
    createdAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "p5",
    email: "aisha.okafor@email.com",
    name: "Aisha Okafor",
    role: "provider",
    phone: "+1 (555) 678-9012",
    categories: ["beauty"],
    rating: 4.9,
    reviewCount: 103,
    hourlyRate: 55,
    bio: "Licensed cosmetologist. Bridal, editorial, and everyday glam.",
    isVerified: true,
    isAvailable: true,
    documentsUploaded: true,
    completedJobs: 289,
    location: { lat: 40.7614, lng: -73.9776, address: "Upper East Side, NY" },
    createdAt: "2023-04-22T00:00:00Z",
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    clientId: "c1",
    providerId: "p1",
    category: "plumbing",
    title: "Kitchen Faucet Repair",
    description: "Leaky faucet in the kitchen needs replacement washer or cartridge.",
    status: "in_progress",
    scheduledDate: "2026-09-14",
    scheduledTime: "10:00 AM",
    address: "123 Main St, Apt 4B, New York, NY 10001",
    location: { lat: 40.7484, lng: -73.9967 },
    estimatedCost: 120,
    createdAt: "2026-09-12T08:30:00Z",
  },
  {
    id: "b2",
    clientId: "c1",
    providerId: "p2",
    category: "cleaning",
    title: "Deep Clean Apartment",
    description: "2-bedroom apartment needs a thorough deep clean before move-in.",
    status: "accepted",
    scheduledDate: "2026-09-15",
    scheduledTime: "2:00 PM",
    address: "456 Oak Ave, New York, NY 10002",
    location: { lat: 40.7282, lng: -73.7949 },
    estimatedCost: 180,
    createdAt: "2026-09-11T14:00:00Z",
  },
  {
    id: "b3",
    clientId: "c2",
    providerId: "p4",
    category: "tutoring",
    title: "SAT Math Prep",
    description: "Need help with SAT math sections. Test in 3 weeks.",
    status: "pending",
    scheduledDate: "2026-09-16",
    scheduledTime: "4:00 PM",
    address: "789 Pine St, New York, NY 10003",
    location: { lat: 40.7309, lng: -73.9872 },
    estimatedCost: 60,
    createdAt: "2026-09-13T09:15:00Z",
  },
  {
    id: "b4",
    clientId: "c1",
    providerId: "p3",
    category: "electrical",
    title: "Ceiling Fan Installation",
    description: "Install new ceiling fan in living room. Wiring already exists.",
    status: "completed",
    scheduledDate: "2026-09-10",
    scheduledTime: "11:00 AM",
    address: "123 Main St, Apt 4B, New York, NY 10001",
    location: { lat: 40.7484, lng: -73.9967 },
    estimatedCost: 150,
    actualCost: 140,
    rating: 5,
    review: "Excellent work! Very professional and quick.",
    createdAt: "2026-09-08T16:00:00Z",
  },
];

export function getCategoryBySlug(slug: ServiceCategory): ServiceItem | undefined {
  return SERVICE_CATEGORIES.find((c) => c.category === slug);
}

export function getProviderById(id: string): Provider | undefined {
  return MOCK_PROVIDERS.find((p) => p.id === id);
}

export function getBookingsForClient(clientId: string): Booking[] {
  return MOCK_BOOKINGS.filter((b) => b.clientId === clientId);
}

export function getBookingsForProvider(providerId: string): Booking[] {
  return MOCK_BOOKINGS.filter((b) => b.providerId === providerId);
}
